bank:
  pos_id: 12345
  pos_auth_key: XXX
  key1: XXX
  key2: XXX
  type: default
  add_signature: true
  gateway_url: 'www.payu.in'

sms:
  pos_id: 56789
  pos_auth_key: XXX
  key1: XXX
  key2: XXX
  type: sms_premium
  add_signature: false