# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd24a81abbc43ce1f997179d94c31020a3d491db4ad3c32cf6ba6f1fc7f237d456829d45de592fbc31ed74ef07b5e783af73f579bf20f99236c256cda30c5a72
  bucket_name: <%= ENV["BUCKET_NAME"] %>
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>


test:
  secret_key_base: b393ae47c6b3129a24e20d11188ca3250042156c086507a214cf0c3372a3e333ef534cf0f3b4435cefd72f218c3e495618b44b6a9809fd363990fabd3604a1b8



# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bucket_name: <%= ENV["BUCKET_NAME"] %>
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
